### ISSUE TITLE
wrong reference in install-magento-environment

### ISSUE THREAD

**Issue by piotrekkaminski** [paliarush/magento2-vagrant-for-developers-packer#1]
The build fails 

==> default: Generation complete.
==> default: + LC_ALL=en_US.UTF-8
==> default: + add-apt-repository ppa:ondrej/php-7.0
==> default: Cannot add PPA: 'ppa:ondrej/php-7.0'.
==> default: Please check that the PPA name or format is correct.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I think it should be ppa:ondrej/php-7.0 -> ppa:ondrej/php7.0

**Comment by paliarush** [comment]
It definitely worked 3 months ago (see [this post](https://www.rosehosting.com/blog/install-php-7-on-ubuntu-14-04/) where repository name is the same "ppa:ondrej/php-7.0"). Maybe something changed since that time. Will check it.

@piotrekkaminski, Thank you for reporting.

**Comment by paliarush** [comment]
Fixed in https://github.com/paliarush/magento2-vagrant-for-developers-packer/commit/ead1bddddc7869b0c9ecc3160a74f27819224a3f
